- name: Run nginx using docker (AWX simple)
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull nginx image
      shell: docker pull nginx:latest

    - name: Run nginx container
      shell: |
        docker rm -f nginx || true
        docker run -d --name nginx -p 80:80 nginx:latest
